create database customer_db;
use customer_db;
show tables;
select * from customer_data;
-- revenue generated by male vs female customers 
select gender,sum(purchase_amount) as total_amount  
from customer_data 
group by gender 
order by total_amount desc ;
-- which customer used discount but still spent more that avg purchase amount 
 select customer_id,purchase_amount
 from customer_data 
 where discount_applied = 'yes' and purchase_amount >= (select avg(purchase_amount) as avg_purchase_amt from customer_data);
 -- which are the top 5 products with highest avg review rating 
 select item_purchased,round(avg(review_rating),2) as avg_product_review 
 from customer_data
 group by item_purchased
 order by avg_product_review desc
 limit 5;
 -- compare the avg purchase amt bwt standard and express shipping 
 select shipping_type,avg(purchase_amount) as revenue  
 from customer_data 
 where shipping_type in ('standard','express')
 group by shipping_type 
 order by revenue desc ;
 -- do subcribed customers spend more ? comapre avg spend and total revenue btw subscribers and non subscribers 
 select subscription_status,count(customer_id) as total_customers,round(avg(purchase_amount),2) as avg_spent,
 round(sum(purchase_amount),2) as total_revenue 
 from customer_data 
 group by subscription_status
 order by total_revenue desc,avg_spent;
 -- which 5 products have the highest percentage of purchases with discount applied 
 select item_purchased,round(100* sum(case when discount_applied = 'yes' then 1 else 0 end)/count(*) ,2) as discount_rate 
 from customer_data
 group by item_purchased 
 order by discount_rate desc 
 limit 5;
 -- segment customers into new , returning , and loyal based on their total no.of their prev purchases and should the count of each degment 
 with customer_type as (
 select customer_id , previous_purchases,
 case 
 when previous_purchases = 1 then 'new'
when previous_purchases between 2 and 10 then 'returning'
 else 'loyal'
 end as 'customer_segment'
 from customer_data ) 
 select customer_segment,count(*) as no_of_customers
 from customer_type
 group by customer_segment ;
 -- what are 3 most purchased products with in each category 
 with item_count as ( 
 select category,item_purchased,count(customer_id) as total_orders,
 row_number() over(partition by category order by count(customer_id) desc) as item_rank 
 from customer_data 
 group by category,item_purchased ) 
 select item_rank,item_purchased,category,total_orders
 from item_count 
 where item_rank <=3;
 -- are customers who are repeat buyers (more that 5 prev purchases) are likely to subscribe 
 select subscription_status , count(customer_id) as reprat_buyers 
 from customer_data
 where previous_purchases > 5 
 group by subscription_status;
 -- what is the revenue contribution of each age group 
 select age_group , sum(purchase_amount) as revenue 
 from customer_data 
 group by age_group 
 order by revenue desc ;
 
 
 
 
 
 
 
 
 